### ISSUE TITLE
Not working with Symfony 7.3 beta 1

### ISSUE THREAD

**Issue by tacman** [ayaou/command-logger-bundle#10]
Here's my command, using Symfony 7.3 beta.  Nothing is being recorded in the logs.

```php
<?php

namespace App\Command;

use Ayaou\CommandLoggerBundle\Attribute\CommandLogger;
use Symfony\Component\Console\Attribute\Argument;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Attribute\Option;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

#[AsCommand('app:log', 'test command_log')]
#[CommandLogger]
class LogCommand
{
	public function __construct()
	{
	}


	public function __invoke(
		SymfonyStyle $io,
		#[Option(description: 'force the command', shortcut: 'f')]
		?bool $force = null,
	): int
	{
		if ($force) {
		    $io->writeln("Option force: $force");
		}
		return Command::SUCCESS;
	}
}
```

**Comment by tacman** [comment]
Actually, even running a 7.2 command isn't showing anything in the logs.

```yaml
# Default configuration for extension with alias: "command_logger"
command_logger:

    # Enable or disable command logging
    enabled:              true

    # Number of days to keep logs before purging
    purge_threshold:      100
    commands:
        - doctrine:fixtures:load

```

Maybe you could add a ->info() message when verbosity is set to indicate that the command itself was logged?
```
 bin/console doctrine:fixtures:load -n -vvv

   > purging database
   > loading App\DataFixtures\App
   > loading App\DataFixtures\AppFixtures
11:46:19 INFO      [app] Dispatching https://sais.wip/account_setup via 127.0.0.1:7080
11:46:19 INFO      [http_client] Request: "POST https://sais.wip/account_setup"
11:46:19 INFO      [http_client] Response: "200 https://sais.wip/account_setup" 0.065588 seconds
```
