### ISSUE TITLE
Support wildcards on commands config

### ISSUE THREAD

**Issue by ayaou** [ayaou/command-logger-bundle#15]
Allow wildcards as `app:*` that will accept all commands starting with `app:`

```yaml
# Default configuration for extension with alias: "command_logger"
command_logger:
    enabled:              true
    purge_threshold:      100
    commands:
        - app:*

```
